import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Utilities/Navbar";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Anjaynime List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={"scroll-smooth"}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
